### ISSUE TITLE
NaomiはMongoDBを使いたい (Bitnami Helm Chart) 

### ISSUE THREAD

**Issue by making** [tanzu-japan/jaguchi-manifests#11]
### Why

**As Naomi**
**I want to MongoDBを使用したい**
**So that アプリデータを永続化するため**

### Acceptance Criteria

```gherkin
Scenario: 
Given Spring Musicがデプロイされて、データがWeb上で更新されている
When Spring MusicのPodを削除する
Then 更新されたデータが残っていること
```

**Notes:**
MongoDBのデプロイにはBitnami Helm Chartを使用し、Direct Secret ReferenceでService Bindingでアプリに接続する。
Secretはsecretgen controllerのSecret Templateで生成する。

* https://github.com/bitnami/charts/tree/master/bitnami/mongodb
* https://github.com/servicebinding/spec#direct-secret-reference
* https://github.com/vmware-tanzu/carvel-secretgen-controller/blob/develop/docs/secret-template.md

**Comment by making** [comment]
## Helm ChartからYAML生成

```
NAMESPACE=<GitHubのアカウント名>
helm repo add bitnami https://charts.bitnami.com/bitnami
helm template -n ${NAMESPACE} music-db bitnami/mongodb --set "auth.usernames[0]=music,auth.databases[0]=music,auth.existingSecret=music-db" > music-db.yaml
```

## Password CRの生成

Secret Templateに設定するキーは、Helm Chartで必須のキー(`mongodb-passwords`, `mongodb-root-password`)と[Spirng Cloud Bindings](https://github.com/spring-cloud/spring-cloud-bindings#mongodb)で期待されているキー(`uri`)

```yaml
cat <<EOF > music-db-password.yaml
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: music-db
  namespace: ${NAMESPACE}
spec:
  secretTemplate:
    type: servicebinding.io/mongodb
    stringData:
      type: mongodb
      uri: mongodb://music:\$(value)@music-db-mongodb:27017/music
      mongodb-passwords: \$(value)
      mongodb-root-password: \$(value)
EOF
```
