### ISSUE TITLE
Alanaはログの転送先としてElasticsearch + Kibanaが欲しい

### ISSUE THREAD

**Issue by making** [tanzu-japan/jaguchi-manifests#12]
### Why

**As Alana**
**I want to ログの転送先としてElasticsearch + Kibanaが欲しい**
**So that トラブルシュートなどにログを見たいから**

### Acceptance Criteria

```gherkin
Scenario: 
Given
When
Then
```

**Notes:**

**Comment by making** [comment]
## Elasticsearch用のnode pool作成

Elasticsearchは専用環境に置きたいが、新規クラスタを作成するのも面倒なので、nodePoolを追加する。taintとlabelをつけて、他のPodがスケジューリングされないようにする。

```yaml
apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: jaguchi
  namespace: ns-tmaki
spec:
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks:
        - 100.96.0.0/11
      serviceDomain: cluster.local
      services:
        cidrBlocks:
        - 100.64.0.0/13
    storage:
      classes:
      - k8s-storage
      defaultClass: k8s-storage
  topology:
    controlPlane:
      tkr:
        reference:
          name: v1.21.6---vmware.1-tkg.1.b3d708a
      vmClass: best-effort-large
      replicas: 3
      storageClass: k8s-storage
    nodePools:
    - name: workers
      vmClass: best-effort-large
      replicas: 5
      storageClass: k8s-storage
      volumes:
      - name: containerd
        mountPath: /var/lib/containerd
        capacity:
          storage: 60Gi
    # ↓追加
    - name: logging
      vmClass: best-effort-large
      replicas: 3
      storageClass: k8s-storage
      taints:
      - key: CriticalAddonsOnly
        effect: NoExecute
      labels:
        role: logging
```

Elasticsearchには`nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution`と`tolerations`を指定する
