### ISSUE TITLE
Naomiはアプリをインターネットに公開したい

### ISSUE THREAD

**Issue by making** [tanzu-japan/jaguchi-manifests#9]
### Why

**As Naomi**
**I want to アプリをインターネットに公開したい**
**So that インターネット上のユーザーにアプリを使ってもらう**

### Acceptance Criteria

```gherkin
Scenario: 
Given Spring Musicがデプロイされている
When VPN外のNetworkからインターネット公開用のURLにアクセスする
Then トップページが表示される
```

**Notes:**

アプリのデフォルトドメイン `*.apps.jaguchi.maki.lol` はVPN内からしかアクセスできない。
[https://github.com/making/tsunagu](Tsunagu) を使用して、jaguchiクラスタをインターネットから `*.run.jaguchi.maki.lol` アクセスできるようにする。
個々のアプリへは [DomainMapping](https://knative.dev/docs/serving/services/custom-domains) CRで`*.run.jaguchi.maki.lol`ドメインを追加することによってTsunagu経由でアクセスできるようにする

**Comment by making** [comment]
## Tsunagu Serverのデプロイ
(省略) Software Desing 4月号のおうちクラウド特集の方法そのままでOracle Cloud上に構築した。
`*.run.jaguchi.maki.lol`のAレコードをパブリックIPに向けた。

**Comment by making** [comment]
## Tsunagu Clientのデプロイ

* TsunaguのCarvel Package Repository追加 https://github.com/tanzu-japan/jaguchi-manifests/commit/f5b8575ac0d69b54a174e35dac84f75a39c23b77
* Tsunagu Client Packageのインストール https://github.com/tanzu-japan/jaguchi-manifests/commit/948d620a97744c7d562777bdf61a2f1cc9950597

**Comment by making** [comment]
## Spring Musicのデプロイ

[こちらのドキュメント](https://github.com/tanzu-japan/jaguchi-manifests/blob/main/docs/onboarding_ja.md#workload%E3%81%AE%E4%BD%9C%E6%88%90)の通りSpring Musicをデプロイする。


```
$ tanzu apps workload get -n ${NAMESPACE} spring-music
# spring-music: Ready
---
lastTransitionTime: "2022-05-17T05:36:01Z"
message: ""
reason: Ready
status: "True"
type: Ready

Pods
NAME                                             STATUS      RESTARTS   AGE
spring-music-00001-deployment-58d65bbb4b-wp9hd   Running     0          62s
spring-music-build-1-build-pod                   Succeeded   0          8m14s
spring-music-config-writer-7qzkb-pod             Succeeded   0          86s

Knative Services
NAME           READY   URL
spring-music   Ready   https://spring-music-making.apps.jaguchi.maki.lol
```

**Comment by making** [comment]
## DomainMappingの作成

```yaml
cat <<EOF > domainmapping.yaml
apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: spring-music-${NAMESPACE}.run.jaguchi.maki.lol
  namespace: ${NAMESPACE}
spec:
  ref:
    name: spring-music
    kind: Service
    apiVersion: serving.knative.dev/v1
EOF
```

```
kubectl apply -f domainmapping.yaml
```

```
$ kubectl get domainmapping -n ${NAMESPACE}
NAME                                       URL                                                READY   REASON
spring-music-making.run.jaguchi.maki.lol   https://spring-music-making.run.jaguchi.maki.lol   True    
```

VPNの外で `https://spring-music-${NAMESPACE}.run.jaguchi.maki.lol` にアクセス

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/106908/168737317-a50d027c-b630-459f-8009-877bff3ae403.png">
